// Code generated by "stringer -type=CardSuit,CardValue"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Spade-0]
	_ = x[Diamond-1]
	_ = x[Club-2]
	_ = x[Heart-3]
	_ = x[suitSize-4]
	_ = x[Joker-5]
}

const _CardSuit_name = "SpadeDiamondClubHeartsuitSizeJoker"

var _CardSuit_index = [...]uint8{0, 5, 12, 16, 21, 29, 34}

func (i CardSuit) String() string {
	if i < 0 || i >= CardSuit(len(_CardSuit_index)-1) {
		return "CardSuit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardSuit_name[_CardSuit_index[i]:_CardSuit_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ace-1]
	_ = x[Two-2]
	_ = x[Three-3]
	_ = x[Four-4]
	_ = x[Five-5]
	_ = x[Six-6]
	_ = x[Seven-7]
	_ = x[Eight-8]
	_ = x[Nine-9]
	_ = x[Ten-10]
	_ = x[Jack-11]
	_ = x[Queen-12]
	_ = x[King-13]
	_ = x[valueSize-14]
}

const _CardValue_name = "AceTwoThreeFourFiveSixSevenEightNineTenJackQueenKingvalueSize"

var _CardValue_index = [...]uint8{0, 3, 6, 11, 15, 19, 22, 27, 32, 36, 39, 43, 48, 52, 61}

func (i CardValue) String() string {
	i -= 1
	if i < 0 || i >= CardValue(len(_CardValue_index)-1) {
		return "CardValue(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CardValue_name[_CardValue_index[i]:_CardValue_index[i+1]]
}
